// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.cssoftware.seguranca.model;

import br.com.cssoftware.seguranca.model.Permissao;
import br.com.cssoftware.seguranca.model.PermissaoDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect PermissaoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PermissaoDataOnDemand: @Component;
    
    private Random PermissaoDataOnDemand.rnd = new SecureRandom();
    
    private List<Permissao> PermissaoDataOnDemand.data;
    
    public Permissao PermissaoDataOnDemand.getNewTransientPermissao(int index) {
        Permissao obj = new Permissao();
        setDescricao(obj, index);
        setNome(obj, index);
        return obj;
    }
    
    public void PermissaoDataOnDemand.setDescricao(Permissao obj, int index) {
        String descricao = "descricao_" + index;
        if (descricao.length() > 100) {
            descricao = descricao.substring(0, 100);
        }
        obj.setDescricao(descricao);
    }
    
    public void PermissaoDataOnDemand.setNome(Permissao obj, int index) {
        String nome = "nome_" + index;
        obj.setNome(nome);
    }
    
    public Permissao PermissaoDataOnDemand.getSpecificPermissao(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Permissao obj = data.get(index);
        Long id = obj.getId();
        return Permissao.findPermissao(id);
    }
    
    public Permissao PermissaoDataOnDemand.getRandomPermissao() {
        init();
        Permissao obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Permissao.findPermissao(id);
    }
    
    public boolean PermissaoDataOnDemand.modifyPermissao(Permissao obj) {
        return false;
    }
    
    public void PermissaoDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Permissao.findPermissaoEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Permissao' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Permissao>();
        for (int i = 0; i < 10; i++) {
            Permissao obj = getNewTransientPermissao(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
