// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.cssoftware.seguranca.model;

import br.com.cssoftware.seguranca.model.Permissao;
import br.com.cssoftware.seguranca.model.PermissaoDataOnDemand;
import br.com.cssoftware.seguranca.model.PermissaoIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PermissaoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PermissaoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PermissaoIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PermissaoIntegrationTest: @Transactional;
    
    @Autowired
    private PermissaoDataOnDemand PermissaoIntegrationTest.dod;
    
    @Test
    public void PermissaoIntegrationTest.testCountPermissaos() {
        Assert.assertNotNull("Data on demand for 'Permissao' failed to initialize correctly", dod.getRandomPermissao());
        long count = Permissao.countPermissaos();
        Assert.assertTrue("Counter for 'Permissao' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PermissaoIntegrationTest.testFindPermissao() {
        Permissao obj = dod.getRandomPermissao();
        Assert.assertNotNull("Data on demand for 'Permissao' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Permissao' failed to provide an identifier", id);
        obj = Permissao.findPermissao(id);
        Assert.assertNotNull("Find method for 'Permissao' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Permissao' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PermissaoIntegrationTest.testFindAllPermissaos() {
        Assert.assertNotNull("Data on demand for 'Permissao' failed to initialize correctly", dod.getRandomPermissao());
        long count = Permissao.countPermissaos();
        Assert.assertTrue("Too expensive to perform a find all test for 'Permissao', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Permissao> result = Permissao.findAllPermissaos();
        Assert.assertNotNull("Find all method for 'Permissao' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Permissao' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PermissaoIntegrationTest.testFindPermissaoEntries() {
        Assert.assertNotNull("Data on demand for 'Permissao' failed to initialize correctly", dod.getRandomPermissao());
        long count = Permissao.countPermissaos();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Permissao> result = Permissao.findPermissaoEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Permissao' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Permissao' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PermissaoIntegrationTest.testFlush() {
        Permissao obj = dod.getRandomPermissao();
        Assert.assertNotNull("Data on demand for 'Permissao' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Permissao' failed to provide an identifier", id);
        obj = Permissao.findPermissao(id);
        Assert.assertNotNull("Find method for 'Permissao' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPermissao(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Permissao' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PermissaoIntegrationTest.testMergeUpdate() {
        Permissao obj = dod.getRandomPermissao();
        Assert.assertNotNull("Data on demand for 'Permissao' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Permissao' failed to provide an identifier", id);
        obj = Permissao.findPermissao(id);
        boolean modified =  dod.modifyPermissao(obj);
        Integer currentVersion = obj.getVersion();
        Permissao merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Permissao' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PermissaoIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Permissao' failed to initialize correctly", dod.getRandomPermissao());
        Permissao obj = dod.getNewTransientPermissao(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Permissao' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Permissao' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Permissao' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PermissaoIntegrationTest.testRemove() {
        Permissao obj = dod.getRandomPermissao();
        Assert.assertNotNull("Data on demand for 'Permissao' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Permissao' failed to provide an identifier", id);
        obj = Permissao.findPermissao(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Permissao' with identifier '" + id + "'", Permissao.findPermissao(id));
    }
    
}
