// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.cssoftware.seguranca.model;

import br.com.cssoftware.seguranca.model.PermissaoIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PermissaoIntegrationTest_Roo_Configurable {
    
    declare @type: PermissaoIntegrationTest: @Configurable;
    
}
